---
title: Explorer HAT buggy
hero_image: images/banner.png
description: Make a very simple buggy using a Raspberry Pi and an Explorer HAT
original_url: https://raspberrypi.org/learning/explorer-hat-buggy
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-1, community-0
interests: robotics
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Choosing a chassis
- title: Add wheels
- title: Connect the Raspberry Pi
- title: Connecting to your Raspberry Pi remotely
- title: Programming the robot
  completion: internal
- title: Adding a GUI
- title: What next?
